INSERT INTO PAYS(nompays) VALUES 
('France'),
('Viet Nam'),
('Turquie'),
('Algérie'),
('--- Inconnu ---'),
('Maroc'),
('Belgique'),
('Slovénie'),
('Liban'),
('Argentine'),
('Allemagne'),
('Tunisie'),
('République Tchèque'),
('Inde'),
('Mexique'),
('Roumanie'),
('Brésil'),
('Suède'),
('Chine'),
('Italie'),
('Fédération de Russie'),
('Colombie'),
('Iran'),
('Suisse'),
('Cameroun'),
('Canada'),
('Équateur'),
('République Arabe Syrienne'),
('Pakistan'),
('Bénin'),
('États-Unis'),
('Côte d"Ivoire'),
('Bulgarie'),
('Madagascar'),
('Yémen'),
('Lituanie'),
('Espagne'),
('Bolivie'),
('Égypte'),
('Portugal'),
('Togo'),
('Chili'),
('Indonésie'),
('Niger'),
('Thaïlande'),
('Myanmar'),
('Djibouti'),
('Taïwan'),
('Maurice'),
('Pays-Bas'),
('Estonie'),
('Pologne'),
('Serbie'),
('Sénégal'),
('Iraq'),
('Burkina Faso'),
('Jamahiriya Arabe Libyenne'),
('Autriche'),
('Grèce'),
('Ukraine'),
('Nigéria'),
('Slovaquie'),
('Nouvelle-Calédonie'),
('Israël'),
('Mali'),
('Afrique du Sud'),
('Bahreïn'),
('Irlande'),
('Albanie'),
('Australie'),
('Pérou'),
('Japon'),
('Rwanda'),
('Géorgie'),
('Ouzbékistan'),
('Arabie Saoudite'),
('Royaume-Uni');

INSERT INTO TYPESUPPORT(natureSupport) VALUES
('Contrat doctoral'),
('CDD (Cat. A)'),
('Fonctionnaire'),
('--- Aucun ---'),
('Stage'),
('--- Inconnu ---'),
('CDI'),
('Doctorant en cotutelle'),
('Invité'),
('Bourse'),
('CDD (Cat. C)'),
('Retraite'),
('Emérite'),
('--- Autre contrat---'),
('CDD (Cat. B)'),
('CDD chercheur'),
('CES');

INSERT INTO CATEGORIE(nomCategorie) VALUES
('NON PERMANENT'),
('PERMANENT'),
('ASSOCIE'),
('EN DISPONIBILITE'),
('DETACHEMENT sortant'),
('DELEGATION entrante'),
('DETACHEMENT entrant'),
('DELEGATION sortante');

INSERT INTO GRADE(statut) VALUES
('Doctorant'),
('Ingénieur'),
('Maître de Conférences Hors Classe'),
('Maître de Conférences Classe Normale'),
('Post Doctorant'),
('Ingénieur de Recherche'),
('Ingénieur d"Etudes'),
('Stagiaire'),
('Maître de Conférences'),
('Chargé de Recherche'),
('ISFP'),
('Chargé de Recherche 2ème Classe'),
('Ingénieur de Recherche 2ème Classe'),
('Assistant Ingénieur'),
('Attaché Temporaire d"Enseignement et de Recherche'),
('Chercheur'),
('Professeur'),
('Directeur de Recherche 2ème Classe'),
('Directeur de Recherche 1ère Classe'),
('Technicien de Classe Exceptionelle'),
('Professeur 2ème Classe'),
('Professeur 1ère Classe'),
('Professeur de Classe Exceptionnelle 1'),
('Chargé de Recherche 1ère Classe'),
('Technicien de Classe Normale'),
('Adjoint technique principal de 2ème classe'),
('Adjoint technique principal de 1ère classe'),
('Adjoint Technique de Recherche'),
('Technicien de la Recherche'),
('Ingénieur d"Etudes 2ème Classe'),
('Ingénieur d"Etudes Classe Normale'),
('Professeur de Classe Exceptionnelle 2'),
('Ingénieur d"Etudes Hors Classe'),
('--- Aucun ---'),
('Chargé de Recherche Classe Normale'),
('Maître de Conférences Hors Classe Echelon Exceptionnel'),
('Attaché d"administration de l"Etat'),
('Directeur de Recherche'),
('Ingénieur de Recherche Hors Classe'),
('Ingénieur de Recherche 1ère Classe'),
('Technicien de Classe Supérieure'),
('--- Inconnu ---'),
('Ingénieur d"Etudes 1ère Classe'),
('Professeur - Praticien Hospitalier'),
('Professeur agrégé'),
('Elève normalien'),
('Professeur Certifié'),
('Adjoint Administratif principal 2ème classe'),
('Adjoint Administratif principal 1ère classe'),
('Adjoint Technique 2ème classe'),
('Apprenti'),
('Maître de Conférences - Praticien Hospitalier'),
('Adjoint Technique 1ère classe');

INSERT INTO SECTION(CoNRS) VALUES
('0.0'),
('6.0'),
('7.0'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('41.0'),
('nan'),
('nan');

INSERT INTO CNU(CNU) VALUES
('0.0'),
('27.0'),
('61.0'),
('26.0'),
('nan'),
('71.0'),
('65.0'),
('nan'),
('63.0'),
('16.0'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan'),
('nan');

INSERT INTO EQUIPE(nomEquipe) VALUES
('Loki'),
('MJOLNIR'),
('NOCE'),
('SequeL'),
('FOX'),
('BioComputing'),
('INOCS'),
('Dolphin'),
('Bonsai'),
('Imagerie Couleur'),
('MIIRE'),
('MOCIS'),
('MINT'),
('Calcul Formel'),
('Spirals'),
('RMoD'),
('ADAM'),
('Algomus'),
('Magnet'),
('SI'),
('SIGMA'),
('SMAC'),
('Émeraude'),
('PADR'),
('DiCOT'),
('--- Inconnue ---'),
('2XS'),
('SHACRA'),
('DreamPal'),
('DaRT'),
('DEFROST'),
('CFHP'),
('OSL'),
('RD2P'),
('SyNeR'),
('ORKAD'),
('BONUS'),
('3D SAM'),
('ToSyMA'),
('SHOC'),
('VALSE'),
('MOSTRARE'),
('BCI'),
('SCOOL'),
('Links'),
('STF'),
('Sequoia'),
('Administration'),
('SoftE'),
('MAP'),
('PIT'),
('MOSES'),
('PERSI'),
('Service technique'),
('CARBON'),
('GRAPHIX'),
('nan'),
('SyCoMoRES'),
('ALCOVE'),
('EAST'),
('CARAMEL'),
('COCOA'),
('SHAMAN');

INSERT INTO EMPLOYEUR(nomEmployeur) VALUES
('Université de Lille'),
('Université Lille 1'),
('Inria Lille'),
('CNRS'),
('--- Inconnu ---'),
('ERASMUS MUNDUS'),
('EDF'),
('ORANGE'),
('Université de Fortaleza - Brésil'),
('CHRU de Lille'),
('Université Lille 2'),
('Institut Mines Telecom'),
('IMT Lille Douai'),
('Ecole des mines de Douai'),
('TECHNOLOGIES'),
('Université Lille 3'),
('RAILENIUM'),
('--- Autre / Other ---'),
('Centrale Lille'),
('NORSYS'),
('ISEN'),
('--- Aucun ---'),
('Centre Oscar Lambret'),
('CHINA SCHOLARSHIP COUNCIL'),
('Université d"Israel'),
('Institut Pasteur de Lille'),
('Université de Bucarest'),
('Université d"Algerie'),
('SAP Research'),
('Google DeepMind '),
('Clic and Walk'),
('GENES DIFFUSION'),
('Université Catholique de Lille'),
('Université de Picardie Jules Verne - Amiens'),
('Institut Catholique de Lille'),
('CNAM'),
('GEMALTO SA'),
('Université du Québec à Montréal'),
('Le livre scolaire'),
('Université de Valenciennes'),
('Campus France'),
('Ecole Normale Supérieure de Paris-Saclay'),
('Ecole Normale Supérieure de Rennes'),
('Université du Japon'),
('Université d"Oran'),
('MESR'),
('IFSTTAR'),
('CEA'),
('Ecole Normale Supérieure de Cachan'),
('Université de Tunisie'),
('Ecole Pluridisciplinaire Internationale de Sousse'),
('Université de Chine'),
('NetAscq'),
('FNRS - Fonds National de la Recherche Scientifique'),
('VEKIA'),
('IPSA'),
('Rectorat'),
('Université du Littoral Côte d"Opale'),
('IRCICA'),
('Société MANDARINE'),
('Université étrangère'),
('HEI - Hautes Ecoles d"Ingénieurs'),
('Université de l"Inde'),
('Naver Labs Europe'),
('CONACYT'),
('Gouvernement algérien'),
('PIXEO Comparateur d"assurances'),
('INNOVIMAX'),
('XEROX '),
('Université de Leuven - Belgique'),
('Université de Rio - Brésil'),
('SCALAIR'),
('Université de Limoges'),
('Université du Liban'),
('Université de Rennes'),
('Polytech"Lille'),
('Université d"Eindhoven - Pays Bas'),
('Institut National Polytechnique de Toulouse'),
('Sté ACSSI'),
('CIM'),
('Université de Coimbra'),
('SATT Nord - Société d"Accélération du Transfert de Technologies'),
('DGA'),
('Ecole Nationale Supérieure Polytechnique  - ENSP du Cameroun'),
('Université de Toulouse'),
('EADS'),
('ALICANTE'),
('LASeR (Lebanese Association for Scientific Research)'),
('Université de Dijon'),
('GIS Global Integrated Solutions'),
('THALES'),
('Inserm'),
('Ecole Polytechnique de Montréal'),
('OSEO'),
('MESRS Côte d"Ivoire'),
('Gouvernement étranger'),
('BTravel'),
('Université de Djibouti'),
('Ecole Normale Supérieure de Lyon'),
('Université Sant"Anna - Italie'),
('FACEBOOK FRANCE'),
('Gouvernement syrien'),
('CRITEO'),
('Université d"Artois'),
('Azm & Saade Association'),
('YNCREA'),
('METROVISION'),
('IDEES 3COM'),
('UMons'),
('Gouvernement chinois'),
('MCQ'),
('Ministère de l"Education Nationale'),
('Axellience'),
('ALTRA Consulting'),
('TOTAL'),
('SAS MOFFI'),
('Fifty Five'),
('ATOS Worldline'),
('Université de Bordeaux'),
('INRETS'),
('DCarte Engineering SA'),
('Université de Belgique'),
('Berger-Levrault'),
('Université de Sfax - Tunisie'),
('Réseaux ferré de France'),
('Université de Nankin'),
('INRA'),
('INSAT - Tunisie'),
('CAPGEMINI'),
('Université d"Evry'),
('Université de Waterloo'),
('AMARIS RESEARCH UNIT'),
('Université Le Havre Normandie'),
('ALTRAN'),
('Université de Technologie de Belfort-Montbéliard (UTBM)'),
('RENAULT SA'),
('ADEME - Agence De l"Environnement et de la Maîtrise de l"Energie'),
('ROBOCATH'),
('ISITCOM'),
('Université de Lasi - Roumanie'),
('VEOLIA'),
('Gouvernement tunisien'),
('Université de Kent - Angleterre'),
('Ecole Polytechnique - l"X'),
('Eye / o'),
('INSERM'),
('Université Pennsylvanie - Etats-Unis'),
('COLLIN SA'),
('Ministère des Affaires Etrangères'),
('Maison de la Simulation'),
('ECREALL'),
('System-X'),
('Université Joseph Ki Zerbo - Ouagadougou - Burkina Faso'),
('ONERA'),
('FRANCE TELECOM'),
('VINTEL'),
('Université de Tunis'),
('TASKER'),
('SAFRAN Sagem'),
('Université de Roumanie'),
('AROLLA'),
('PROVE & RUN'),
('CCAMY'),
('Ecole Nationale Supérieure de Mécanique et des Microtechniques'),
('Université d"Angers'),
('Squoring Technologie'),
('BOMBARDIER TRANSPORT'),
('Fondation Mines Paristech'),
('Université du Maroc'),
('Université d"Iran'),
('EOMYS Engineering'),
('Usilink / Wygwam'),
('Université du Cameroun'),
('Go Touch VR'),
('OVH.com Innovation is Freedom'),
('Strat & logic '),
('SNCF'),
('Université d"Alep -Syrie'),
('Ministère de l"Intérieur');

INSERT INTO CIVILITE(genre) VALUES
('M'),
('Mme');

INSERT INTO DIRECTEURTHESE(directeurThese) VALUES
('du Hardy Gérard'),
('nan'),
('Le Descamps Charles'),
('Regnier Josette'),
('Blot Denis'),
('Fournier Vincent-Martin'),
('Grondin Éric'),
('Germain Jacques'),
('de la Michel Louis'),
('Benzema Anaïs'),
('Le Turpin Claude'),
('Arnaud Augustin'),
('Buisson Raymond'),
('Wagner-Arnaud Bertrand'),
('Besnard-Bousquet Jules'),
('Huet Richard'),
('Remy Charles'),
('Leroy Bertrand'),
('Germain Marcel'),
('Durand Mathilde'),
('Hardy-Lambert Noël'),
('de la Collet Yves'),
('Legros-Mercier Luc'),
('Faivre Bernard'),
('De Oliveira Victor'),
('Maury Gérard'),
('Leblanc Philippe'),
('Cohen René'),
('Durand Joseph'),
('du Lagarde Augustin'),
('Lenoir Luc'),
('Le Morvan Patrick'),
('Le Albert Matthieu'),
('Lefevre Denis'),
('Perrot Roland'),
('Coulon Stéphane'),
('Gimenez-Garcia Margaux'),
('Jourdan Rémy'),
('Gilbert Nath'),
('Hebert Lucas'),
('Morvan Joseph'),
('Ledoux Timothée'),
('Ribeiro-Delaunay Gabriel'),
('Rossi Antoine'),
('Descamps Philippe'),
('Gay-Baron Guy'),
('Schmitt William'),
('de Michel Paul'),
('Blanchet-Bernard Victor'),
('Nicolas Jean'),
('Cohen Arthur'),
('Pasquier René'),
('Robert-Herve Thibault'),
('Leroy Daniel'),
('Clement-Tessier Alfred'),
('Lelievre Frédéric'),
('David Xavier'),
('Bernier Marc'),
('Dos Santos Joseph'),
('du Jacquet Théophile'),
('Lemaire Xavier-Zacharie'),
('Le Leclercq Isaac'),
('Charrier Cécile'),
('Adam Honoré'),
('Gautier Étienne'),
('Pineau-Bonnet Robert'),
('Leduc Isaac-Patrick'),
('Michel Olivier'),
('Blanchet-Grenier Paul'),
('du Barthelemy Émile'),
('Besnard Grégoire'),
('Rolland Guy'),
('Bertin Jean'),
('de la Marie Jules'),
('Fischer Stéphane'),
('Martins Roger'),
('Garnier Raymond'),
('Riviere Noël'),
('Poirier Bernard-Patrick'),
('Raymond-Remy Hugues'),
('Launay David'),
('Breton-Allain Maurice'),
('Chauvin Isaac'),
('Meunier Claude-Dominique'),
('Vincent Charles-Franck'),
('Ribeiro-Laroche Sébastien'),
('Le Marion Alphonse'),
('Chevallier Célina'),
('Dufour Amélie'),
('Gerard Vincent-Robert'),
('de Smet Caroline'),
('Merle Guy'),
('de la Vallet Guy'),
('De Sousa-Clement Richard'),
('Germain Alphonse'),
('Loiseau Denise'),
('Gautier Éric'),
('Hernandez Bertrand-Isaac'),
('Vallet-Le Goff Xavier'),
('Martins Denis'),
('Cousin Thierry-Dominique'),
('Poirier Pénélope'),
('Brunel Arthur'),
('Guillon Gérard'),
('Muller Raymond'),
('Pichon Édouard-Gérard'),
('Gros Joseph-Nicolas'),
('de la Descamps Édouard'),
('Fernandez Hugues'),
('Pires Marcel'),
('Lecomte Alfred'),
('de Chevallier Léon'),
('Rolland Margaud'),
('Becker-Fleury Jérôme'),
('de la Bousquet William'),
('Gillet Thibault'),
('Gilles-Dupuis André'),
('Pascal Pierre'),
('Colin Denise'),
('Lefevre-Robin Marine'),
('Cordier Victor'),
('Grondin-Paul Théodore'),
('Barbier Auguste'),
('Marechal Gérard'),
('Laroche Alfred'),
('Weiss Henri'),
('Bousquet Jules'),
('Chevalier Jules-Jacques'),
('Legrand Marcelle'),
('Mace Josette');

\copy PERSONNE(nom,prenom,dateNaissance,dateArriveLabo,idCivilite,idPays,idStatut,idCNU,idSection) from 'personne.csv' delimiter ',';
